### ISSUE TITLE
DataError: No numeric types to aggregate

### ISSUE THREAD

**Issue by keyuchen21** [jxzly/Kaggle-American-Express-Default-Prediction-1st-solution#5]
for the file from S2_manual_feature.py.
I got following errors.

Could you help me take a look?
![image](https://github.com/jxzly/Kaggle-American-Express-Default-Prediction-1st-solution/assets/54015474/bde6f008-b428-4434-b4da-31ad41f8da70)

**Comment by keyuchen21** [comment]
not sure what happened, but after I change n_cpu = 16 to 32, then the problem was solved

**Comment by jxzly** [comment]
#2 You can try df['S_2'] = df['S_2'].apply(lambda x:int(x.replace('-','')))
